# Generated by Django 2.2 on 2021-08-24 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='end_date',
            field=models.DateField(default=datetime.date(2021, 8, 24)),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='publication_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
